### ISSUE TITLE
压缩后的文件不能在电脑上解压缩

### ISSUE THREAD

**Issue by Kiovee** [yanbober/android-7zip#1]
这个库压缩的时候注意2点：
第一个参数不能传入文件夹进行压缩，只能传入文件，不然报错；
第二个参数传入的是文件名，必须带有后缀，比如.7z，不然不能使用unzip()解压缩

解压缩的时候需要注意1点：
第二个参数看着像是一个目录，其实是一个文件容器。

注意以上几点，在手机上测试可以正确的压缩和解压缩，但是把压缩后的文件放在MacOS、Win10和Linux系统都不能解压缩成功，请问这是什么原因呢？

**Comment by yanbober** [comment]
。。。还没做完，还在开发
